# Generated by Django 5.2.5 on 2025-08-25 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logacionamento',
            name='acao',
            field=models.CharField(choices=[('LIGADO', 'Ligado'), ('DESLIGADO', 'Desligado'), ('MANUTENCAO_INICIO', 'Manutenção Iniciada'), ('MANUTENCAO_FIM', 'Manutenção Finalizada')], max_length=20),
        ),
    ]
