# Generated by Django 5.2.5 on 2025-08-25 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='motores/')),
                ('localizacao', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('corrente', models.FloatField(blank=True, help_text='Corrente em Ampères (A)', null=True)),
                ('potencia', models.FloatField(blank=True, help_text='Potência em Watts (W)', null=True)),
                ('tensao', models.CharField(blank=True, help_text='Ex: 110V, 220V', max_length=50)),
                ('ligado', models.BooleanField(default=False)),
                ('em_manutencao', models.BooleanField(default=False)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogAcionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('LIGADO', 'Ligado'), ('DESLIGADO', 'Desligado'), ('MANUTENCAO_INICIO', 'Entrou em Manutenção'), ('MANUTENCAO_FIM', 'Saiu de Manutenção')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('motor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.motor')),
            ],
        ),
    ]
