# Generated by Django 4.2.14 on 2025-09-16 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0003_logacionamento_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='motor',
            name='grupoMotor',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.group'),
        ),
    ]
