# Generated by Django 4.2.14 on 2025-09-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0004_motor_grupomotor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motor',
            name='grupoMotor',
        ),
        migrations.AddField(
            model_name='motor',
            name='grupoMotor',
            field=models.ManyToManyField(blank=True, related_name='motores', to='auth.group'),
        ),
    ]
