# Generated by Django 4.2.14 on 2025-09-17 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_motor_grupomotor_motor_grupomotor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motor',
            old_name='grupoMotor',
            new_name='grupos',
        ),
    ]
