# Generated by Django 4.2.14 on 2025-09-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0006_rename_grupomotor_motor_grupos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motor',
            name='grupos',
            field=models.ManyToManyField(related_name='motores', to='auth.group'),
        ),
    ]
