# Generated by Django 5.2.5 on 2025-08-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monitoriamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataHora', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora')),
                ('mensagem', models.CharField(max_length=100, null=True, verbose_name='Mensagem')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, null=True, verbose_name='Nome')),
                ('modelo', models.CharField(max_length=10000, null=True, verbose_name='Modelo')),
                ('numeroSerial', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Numero Serial')),
                ('corrente', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Corrente')),
                ('potencia', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Potencia')),
                ('tensao', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Tensao')),
                ('descricao', models.CharField(max_length=100, null=True, verbose_name='Descrição')),
                ('localizacao', models.CharField(max_length=100, null=True, verbose_name='Localização')),
                ('imagem', models.CharField(max_length=100, null=True, verbose_name='Imagem')),
            ],
        ),
    ]
